### ISSUE TITLE
Feature request: icon position/gravity

### ISSUE THREAD

**Issue by stam66** [revig/universal-button-widget#1]
Dear Ralf, thanks for this excellent widget, there isn't really much at all to fault it.
The only missing feature is FileMaker Pro-style positioning of the SVG icon (left/top/right/bottom), akin to gravity on an LC button graphic and I'm hoping you'd consider this feature request...
Many thanks,
Stam

**Comment by revig** [comment]
Hi Stam, thanks very much for your request. Now that you write, I think it would actually be good to have the option to place the icon of the widget independently of the label, analogous to the default button. However, this would require a size property for the icon. I will definitely look into it and keep you informed. Warm regards and thanks for the kind words,
Ralf

**Comment by stam66** [comment]
If i could combine that with a 2nd feature request - could resizing the SVG be decoupled from button size?
Or maybe offer a choice if should resize with button or be adjusted manually?
Again, taking a cue from FileMaker Pro's buttons, a slider that adjusts the SVG size makes it easier to manage custom layouts than having to adjust button size. Would be useful for some situations and hopefully may fit in with reworking the SVG icon...

**Comment by revig** [comment]
I will add a property "iconSizeRatio" adjustable via a slider.

**Comment by revig** [comment]
Hi Stam, the new version is out.

**Comment by stam66** [comment]
Works really very well! You are a credit to the community, thank you Ralf!
