### ISSUE TITLE
Error with v1.1.0

### ISSUE THREAD

**Issue by wheninspace** [revig/universal-button-widget#2]
Hi Ralf - I installed v1.1.0 and opened a stack using several universal buttons (as of v1.0.6).
The buttons would not show, instead got this error message:
"array key does not exist"
LCB line: 711

Reinstalled v1.0.6 and all works again.

Hope there's an easy fix. I use your universal-button everywhere nowadays - thanks for this great resource! :)

**Comment by revig** [comment]
Sorry about that, a fix is on it's way.

**Comment by revig** [comment]
Hi Andreas, the fixed version is out. Warm regards.

**Comment by wheninspace** [comment]
Wow, thanks! Now it works perfectly!
