### ISSUE TITLE
Localisation and formattedwidth

### ISSUE THREAD

**Issue by trevixdesign** [revig/universal-button-widget#4]
Great work !!! thanks.
Having languange localisation in my standalone, the label of the UBW may vary in length.
I noticed that the widget does not account for formattedwidth.
Most of my buttons have the SVG icon on the left and the label text on the right, right aligned.
Even if place the UBW in a group, after changing the widget label, the formattedwidth always report 0, both of the widget and of the group.
Am I missing something?
Thanks again. Keep improving this product, please.

**Comment by revig** [comment]
Thanks very much for the kind words. Will look into it as soon as possible.

**Comment by revig** [comment]
There is a brand new version 1.3.0. This version includes a new property "ubFormattedWidth". Let's see if it fits your purpose. Please check out the documentation.
